@Library('robot-shop') _

pipeline {
    agent any

    environment {
        git_url = 'https://github.com/robot-shop-DevOps/robot-shop-cart-microservice.git'
        ecr_url = 'public.ecr.aws/v1g8i1q6'
        aws_region_ecr = 'us-east-1'
        aws_creds = credentials('ECR_SA')
        image_name = 'cart-ms' 
        project = 'robot-shop' 
        namespace = 'robot-shop-pre'
        release = 'cart-microservice'    
    }
    
    stages {
        stage('Checking dependencies') {
            steps {
                script {
                    checkDependencies()
                }
            }
        }

        stage('Checkout code') {
            steps {
                echo "Checking out code from Git SCM"

                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: '466bfd9a-0b0b-4602-9e7c-2351a7eefce2', url: env.git_url]])
            }
        }

        stage('Login to ECR') {
            steps {
                script {
                    ecr([
                        region = env.aws_region_ecr,
                        url    = env.ecr_url
                    ])
                }
            }
        }

        stage('Build & Push docker image') {
            steps {
                script {
                    docker([
                        gitCommit = env.GIT_COMMIT,
                        imageName = env.image_name,
                        ecrUrl    = env.ecr_url
                    ])
                }
            }
        }

        stage('Validate & Deploy helm charts') {
            steps {
                script {
                    helm([
                        release   = env.release,
                        namespace = env.namespace,
                        ecrUrl    = env.ecr_url,
                        imageName = env.image_name,
                        imageTag  = env.image_tag
                    ])
                }
            }
        }
    }
}