microservice: cart
replicas: 1
container:
  image:
    repo: ${ECR_URL}      # <-- placeholder
    version: ${IMAGE_TAG}    # <-- placeholder
    pullPolicy: IfNotPresent
  port: 8080
service:
  type: ClusterIP
  port: 8080