microservice: cart
replicas: 1
container:
  image:
    repo: <ECR_URL>       # <-- placeholder
    version: <Version>    # <-- placeholder
    pullPolicy: IfNotPresent
  port: 8080
service:
  type: ClusterIP
  port: 8080