apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.cart.microservice }}-service

spec:
  type: {{ .Values.cart.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.cart.microservice }}
    {{- range $key,$value := .Values.cart.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  ports:
  - name: http
    port: {{ .Values.cart.service.port }}