apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.microservice }}-deployment
  labels:
    service: {{ .Values.microservice }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.microservice }}
  template:
    metadata:
      labels:
        service: {{ .Values.microservice }}
    spec:
      containers:
      - name: {{ .Values.microservice }}
        image: "{{ .Values.container.image.repo }}:{{ .Values.container.image.version }}"
        imagePullPolicy: {{ .Values.container.image.imagePullPolicy }}
        ports: 
        - containerPort: {{ .Values.container.port }}
        env:
        - name: INSTANA_AUTO_PROFILE
          value: "true"
        - name: REDIS_HOST
          value: redis-service
        - name: CATALOGUE_HOST
          value: catalogue-service