apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.microservice }}-service

spec:
  type: {{ .Values.service.type }}
  selector:
    service: {{ .Values.microservice }}
  ports:
  - name: http
    port: {{ .Values.service.port }}