apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Values.cart.microservice }}-deployment
  labels:
    service: {{ .Values.cart.microservice }}

spec:
  replicas: {{ .Values.cart.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.cart.microservice }}
  template:
    metadata:
      labels:
        service: {{ .Values.cart.microservice }}
    spec:
    {{ if eq .Values.env "pre" }}
      topologySpreadConstraints: 
{{ .Values.cart.topologySpreadConstraints | toYaml | indent 8 }}
    {{ end }}
      containers:
      - name: {{ .Values.cart.microservice }}
        image: "{{ .Values.cart.container.image.repo }}:{{ .Values.cart.container.image.version }}"
        imagePullPolicy: {{ .Values.cart.container.image.imagePullPolicy }}
        ports: 
        - containerPort: {{ .Values.cart.container.port }}
        env:
{{ .Values.cart.container.env | toYaml | indent 8 }}