apiVersion: v1

kind: Service

metadata:
  labels:
    service: {{ .Values.redis.microservice }}
  name: {{ .Values.redis.microservice }}-service
  
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: {{ .Values.redis.microservice }}    
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    service: {{ .Values.redis.microservice }}