apiVersion: v1

kind: Service

metadata:
  labels:
    service: {{ .Values.redis.microservice }}
  name: {{ .Values.redis.microservice }}-service
  
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: {{ .Values.redis.microservice }}    
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.redis.microservice }}
    {{- range $key,$value := .Values.redis.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}