name: Build and Deploy cart microservice to Development

on:
  push:
    branches-ignore:
      - 'main'   

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/microservices-nodesjs.yaml@main
    with:
      MICROSERVICE: cart
      IMAGE: cart
      NAMESPACE: cart-microservice
      RELEASE: cart
      WORKING_DIR: ./cart
      DOCKERFILE_PATH: ./cart
    secrets: inherit